<?php

declare(strict_types=1);

use Infrangible\CatalogProductOptionPromote\Block\Product\View\Options\Type\Text;
use Magento\Catalog\Api\Data\ProductCustomOptionInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Text $block */

$option = $block->getOption();
$item = $block->getItem();
$class = $option->getIsRequire() ? ' required' : '';
?>

<div class="field<?php if ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_AREA) {echo ' textarea';} ?><?= /* @noEscape */ $class; ?>">
    <label class="label" for="cart_<?= $escaper->escapeHtmlAttr($item->getId()); ?>_<?= $escaper->escapeHtmlAttr($option->getId()); ?>_text">
        <span><?= $escaper->escapeHtml($option->getTitle()); ?></span>
        <?= /* @noEscape */ $block->getFormattedPrice(); ?>
    </label>
    <div class="control">
        <?php if ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_FIELD): ?>
            <?php $textValidate = null;
            if ($option->getIsRequire()) {
                $textValidate['required'] = true;
            }
            if ($option->getMaxCharacters()) {
                $textValidate['maxlength'] = $option->getMaxCharacters();
            }
            $textValidate['validate-no-utf8mb4-characters'] = true;
            ?>
            <input type="text"
                   id="cart_<?= $escaper->escapeHtmlAttr($item->getId()); ?>_<?= $escaper->escapeHtmlAttr($option->getId()); ?>_text"
                   class="input-text product-custom-option"
                   <?php if (! empty($textValidate)): ?>data-validate="<?= $escaper->escapeHtml(json_encode($textValidate)); ?>"<?php endif; ?>
                   name="cart[<?= $escaper->escapeHtmlAttr($item->getId()); ?>][options][<?= $escaper->escapeHtmlAttr($option->getId()); ?>]"
                   data-selector="cart[<?= $escaper->escapeHtmlAttr($item->getId()); ?>][options][<?= $escaper->escapeHtmlAttr($option->getId()); ?>]"
                   value="<?= $escaper->escapeHtml($block->getDefaultValue()); ?>"/>
        <?php elseif ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_AREA): ?>
            <?php
            $textAreaValidate = null;
            if ($option->getIsRequire()) {
                $textAreaValidate['required'] = true;
            }
            if ($option->getMaxCharacters()) {
                $textAreaValidate['maxlength'] = $option->getMaxCharacters();
            }
            $textAreaValidate['validate-no-utf8mb4-characters'] = true;
            ?>
            <textarea id="cart_<?= $escaper->escapeHtmlAttr($item->getId()); ?>_<?= $escaper->escapeHtmlAttr($option->getId()); ?>_text"
                      class="product-custom-option"
                      <?php if (!empty($textAreaValidate)): ?>data-validate="<?= $escaper->escapeHtml(json_encode($textAreaValidate)); ?>"<?php endif; ?>
                      name="cart[<?= $escaper->escapeHtmlAttr($item->getId()); ?>][options][<?= $escaper->escapeHtmlAttr($option->getId()); ?>]"
                      data-selector="cart[<?= $escaper->escapeHtmlAttr($item->getId()); ?>][options][<?= $escaper->escapeHtmlAttr($option->getId()); ?>]"
                      rows="5"
                      cols="25"><?= $escaper->escapeHtml($block->getDefaultValue()); ?></textarea>
        <?php endif; ?>
        <?php if ($option->getMaxCharacters()): ?>
            <p class="note note_<?= $escaper->escapeHtmlAttr($option->getId()); ?>">
                <?= $escaper->escapeHtml(__('Maximum %1 characters', $option->getMaxCharacters())); ?>
                <span class="character-counter no-display"></span>
            </p>
        <?php endif; ?>
    </div>
    <?php if ($option->getMaxCharacters()): ?>
        <script type="text/x-magento-init">
            {
                "[data-selector='cart[<?= $escaper->escapeHtmlAttr($item->getId()); ?>][options][<?= $escaper->escapeJs($option->getId()); ?>]']": {
                    "Magento_Catalog/js/product/remaining-characters": {
                        "maxLength":  "<?= (int)$option->getMaxCharacters(); ?>",
                        "noteSelector": ".note_<?= $escaper->escapeJs($option->getId()); ?>",
                        "counterSelector": ".note_<?= $escaper->escapeJs($option->getId()); ?> .character-counter"
                    }
                }
            }
        </script>
    <?php endif; ?>
</div>
